version: "3.9"

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notifications
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/notifications?sslmode=disable
      REDIS_URL: redis://redis:6379
      WEBHOOK_SITE_URL: ${WEBHOOK_SITE_URL:-https://webhook.site/e279ace8-0d47-4ab6-ac42-a2545310dc1f}
      SERVER_PORT: 8080
      WORKER_CONCURRENCY: 10
      LOG_LEVEL: info
      MAX_RETRIES: 5
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  asynqmon:
    image: hibiken/asynqmon
    platform: linux/amd64
    ports:
      - "8081:8080"
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data:
